PrDev (#44)
* Force ProtoBuf 3.5.1 (#79)

This will fix error:

[...]
  File "C:\Python27\lib\site-packages\google\protobuf\descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified module could not be found.

* Weatherlogging degree symbol (#71)

* Add ° to Weather Logging

* Move from .info to .debug

* Add Idle / Busy counter to status page (#68)

* Add Idle/Busy to Status Page

* Add Prio Notify switch (#65)

* Add Prio Notify Switch

* trims discord guilds and roles of white spaces (#75)

* [Stock-RM] Cleanup routine and TTH Fix (#73)

* Latest TTH fix and cleanup routine of StockRM + OPTIMIZE TABLE call after cleanup

* Moved weather

* Fix typos...

* Add filename for dynamic rarity (#81)

* add filename for dynamic rarity as option

* [Stock-RM] Efficiently exclude hidden Pokemon. (#85)

* Efficiently exclude hidden Pokemon.

* Adds #ignorelist-file to config.ini.example (#93)

* Adds #ignorelist-file to config.ini.example

* fix indent

* Solve all travis  (#97)

I travisly you